name: Send Watchtower to Kindle

on:
  schedule:
    # Runs on the 1st of every month at 08:00 UTC
    - cron: "0 8 1 * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: 'Set up HLint'
        uses: haskell-actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: src/
          fail-on: warning

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run script
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          KINDLE_EMAIL: ${{ secrets.KINDLE_EMAIL }}
        run: nix run .#
